Require Import Repl.
(*
Canonical assignments from a local rule (doc/main.tex, Lemma 4.2). A rule `r η l ξ` says that the
child with label `l` of a node with target `η` has target `ξ`. The assignment `Tr r η` is
defined from it by recursion on the path, so coherence reduces to conditions at one node.
*)

Import PSet Mat.

Lemma Label_Equiv_refl (l : Label) : Label_Equiv l l.
destruct l; constructor; apply Equiv_refl.
Qed.

Section S.
Context {D : PSet -> PSet} {U : PSet}.

(*- The assignment generated by a rule, with root target `η`. *)
Inductive Tr (r : PSet -> Label -> PSet -> Prop) (η : PSet) :
    Path -> PSet -> Prop :=
  | Tr_nil {t} : η ≈ t -> Tr r η nil t
  | Tr_cons {p t l ξ} : Tr r η p t -> r t l ξ -> Tr r η (l :: p) ξ.

(*- The conditions on a rule, relative to a class `C` of targets. *)
Class Rule (D : PSet -> PSet) (U : PSet)
    (r : PSet -> Label -> PSet -> Prop) (C : PSet -> Prop) : Prop := {
  func : forall {η l ξ ξ'}, r η l ξ -> r η l ξ' -> ξ ≈ ξ';
  resp : forall {η η' : PSet} {l l' : Label} {ξ ξ' : PSet},
    η ≈ η' -> Label_Equiv l l' -> ξ ≈ ξ' -> r η l ξ -> r η' l' ξ';
  C_resp : forall {η η' : PSet}, η ≈ η' -> C η -> C η';
  (*- children have targets that are elements, and stay in the class *)
  mem : forall {η l ξ}, C η -> r η l ξ -> ξ ∈ η /\ C ξ;
  (*- a target is the union of the successors of the targets of the available children *)
  sup : forall {η G}, C η -> (forall x, x ∈ G <-> exists ζ, r η a ζ /\ x ∈ ζ) ->
    forall x, x ∈ η <-> exists l ξ, Avail D U G l /\ r η l ξ /\ x ∈ succ ξ
  }.

Section Rule.
Context {r : PSet -> Label -> PSet -> Prop} {C : PSet -> Prop}
  (hr : Rule D U r C).
(*include hr*)

Lemma tr_func {η p t t'} (h : Tr r η p t) (h' : Tr r η p t') : t ≈ t'.
revert t' h'; induction h; intros.
*inversion_clear h' as [? e _e|].
 apply Equiv_symm in H; apply Equiv_trans with (1:=H); trivial.
*inversion_clear h' as [|? η1 ?? h0 h1].
 apply IHh in h0.
 revert  h1; apply func.
revert H; apply resp; [trivial|apply Label_Equiv_refl|apply Equiv_refl].
Qed.

Lemma tr_C {η p t} (hη : C η) (h : Tr r η p t) : C t.
induction h.
*revert hη; apply C_resp; trivial.
*edestruct (@mem _ _ _ _ hr) with (1:=IHh) (2:=H); trivial.
Qed.

Lemma tr_cons_iff {η p t l ξ} (h : Tr r η p t) : Tr r η (l :: p) ξ <-> r t l ξ.
split; intros tr.
*inversion_clear tr as [|? η1 ?? h0 h1].
 revert h1; apply resp; [|apply Label_Equiv_refl|apply Equiv_refl].
 revert h0 h; apply tr_func. 
*eapply Tr_cons with (1:=h)(2:=tr).
Qed.

Lemma tr_resp_root {η η' p t} (e : η ≈ η') (h : Tr r η p t) : Tr r η' p t.
clear hr.
induction h.
*apply Equiv_symm in e.
 constructor; apply Equiv_trans with (1:=e); trivial.
*apply Tr_cons with (1:=IHh) (2:=H).
Qed.

Lemma coherent {η} (hη : C η) : Coherent D U (Tr r η) /\ Tr r η nil η.
split; [|constructor; apply Equiv_refl]. 
split.
*intros p t t' h e.
 destruct h as [|q η1 l1 ξ1 h1 e1]; [constructor; eauto using Equiv_trans|].
 apply Tr_cons with (1:=h1).
 revert e1; apply resp; [apply Equiv_refl|apply Label_Equiv_refl|];trivial.
*intros ??? h h'; apply tr_func with (1:=h) (2:=h').
*intros l l' p t e h.
 inversion_clear h as [|? η1 ?? h0 h1].
 apply Tr_cons with (1:=h0).
 revert h1; apply resp; [apply Equiv_refl|trivial|apply Equiv_refl].
*intros l p t t' h h'.
 inversion_clear h as [|? η1 ?? h0 h1].
 eapply mem_congr_right;[apply tr_func with (1:=h')(2:=h0)|].
 eapply mem with (2:=h1).
 eapply tr_C with (2:=h0); trivial.
*intros p t G h hG x.
 rewrite @sup with (G:=G) (1:=hr).
 +apply ex_morph; intros l.
  apply ex_morph; intros t'.
  apply and_iff_morphism; [reflexivity|].
  apply and_iff_morphism; [|reflexivity].
  symmetry; apply tr_cons_iff; trivial.
 +eapply tr_C with (2:=h); trivial.
 +intros z; red in hG; rewrite hG.
  apply ex_morph; intros ζ.
  apply and_iff_morphism; [|reflexivity].
  apply tr_cons_iff; trivial.
Qed.

(*- Replacement for functional relations whose values are in the class of a rule. *)
Lemma replacement (s : PSet) (hU : U = s) (φ : PSet -> PSet -> Prop)
    (φ_resp : forall {x x' y y'}, x ≈ x' -> y ≈ y' -> φ x y -> φ x' y')
    (φ_func : forall {x y y'}, x ∈ s -> φ x y -> φ x y' -> y ≈ y')
    (φ_C : forall {x y}, x ∈ s -> φ x y -> C y) :
    exists img : PSet, forall y, y ∈ img <-> exists x, x ∈ s /\ φ x y.
subst s.
apply @Repl.replacement with (C:=C) (D := D) (T := Tr r); trivial.
*intros η hη; apply coherent; trivial.
*intros ???? e h; eapply tr_resp_root with (2:=h); trivial.
Qed.

End Rule.
End S.

Print Assumptions replacement.
